// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyerfgvuwvxtebsufbxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5ZXJmZ3Z1d3Z4dGVic3VmYnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNTMyMzQsImV4cCI6MjA3NzcyOTIzNH0.Sawg3qmqtb1NGSOkHxgkYdVgBGRElUZFKdYtnysZjp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});